[package]
name = "office-impress"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Presentation model, themes, and PPTX read/write for rust-office Impress"
rust-version.workspace = true

[dependencies]
office-core = { workspace = true }
serde = { workspace = true, features = ["rc"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
zip = { workspace = true }
quick-xml = { workspace = true }
image = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
