[package]
name = "office-format"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Document serialization (JSON + ODT) for rust-office"
rust-version.workspace = true

[dependencies]
office-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
zip = { workspace = true }
quick-xml = { workspace = true }
printpdf = { workspace = true }

[dev-dependencies]
image = { workspace = true }
zip = { workspace = true }
